--for test purposes
ShootableProjectile["shell1"] = true
ShootableProjectile["shell2"] = true
ShootableProjectile["shell3"] = true
ShootableProjectile["shell4"] = true
ShootableProjectile["shell5"] = true
ShootableProjectile["shell6"] = true
ShootableProjectile["shell7"] = true
ShootableProjectile["shell8"] = true
ShootableProjectile["shell9"] = true
ShootableProjectile["shell10"] = true
ShootableProjectile["shell11"] = true
ShootableProjectile["shell12"] = true
ShootableProjectile["shell13"] = true
ShootableProjectile["shell14"] = true
ShootableProjectile["shell15"] = true
ShootableProjectile["shell16"] = true
ShootableProjectile["shell17"] = true
ShootableProjectile["shell18"] = true
ShootableProjectile["shell19"] = true
ShootableProjectile["shell20"] = true

